const products = [
  {
    _id: '1',
    name: 'Bag Mıchael kors',
    image: '/images/michaelcors.jpg',
    description: 'Measures up to 35 cm tall by 24 cm',
    brand: 'Michael kors',
    category: 'Bag',
    price: 50.5,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Bag Mıchael kors small',
    image: '/images/michaelcorssmall.jpg',
    description: 'MK measures up to 28 cm tall by 21 cm',
    brand: 'Michael kors',
    category: 'Bag',
    price: 53.99,
    countInStock: 0,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Marc jakobs mini boy',
    image: '/images/marcjacobs.jpg',
    description: 'Marc jakobs mini boy measures up to 19 cm tall by 11 cm',
    brand: 'Marc jakobs',
    category: 'Bag',
    price: 55.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Louis Vuitton ALMA MM BOY ',
    image: '/images/louisvuitton.jpg',
    description: 'Louis Vuitton ALMA MM BOY measures up to 28 cm tall by 19 cm',
    brand: 'Louis Vuitton',
    category: 'Bag',
    price: 60.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Luıs vuıtton spedy',
    image: '/images/louisbig.jpg',
    description: 'Luıs vuıtton spedy measures up to 33 cm tall by 24 cm',
    brand: 'Luıs vuıtton',
    category: 'Bag',
    price: 58.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Dıor tote',
    image: '/images/christiandior.jpg',
    description: 'Dıor tote easures up to 42 cm tall by 31 cm',
    brand: 'Dıor',
    category: 'Bag',
    price: 80.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
